export interface WhiteboardNode {
  id: string;
  type: 'bookmark' | 'tab' | 'note';
  position: { x: number; y: number };
  width?: number;
  height?: number;
  data: {
    title: string;
    url?: string;
    content?: string; // for notes
    favicon?: string;
    screenshot?: string; // base64
    description?: string;
    tags?: string[];
    color?: string;
  };
  createdAt: string;
}

export interface GroupFrame {
  id: string;
  title: string;
  color: string;
  nodeIds: string[];
  position: { x: number; y: number };
  size: { width: number; height: number };
  autoGenerated: boolean;
  criteria?: 'domain' | 'tags' | 'manual';
}

export interface Tag {
  id: string;
  label: string;
  color: string;
}

export type TagColor = 'red' | 'blue' | 'green' | 'purple' | 'yellow' | 'orange' | 'slate';

export const TAG_COLORS: Record<TagColor, string> = {
  red: '#f1f5f9',
  blue: '#f1f5f9',
  green: '#f1f5f9',
  purple: '#f1f5f9',
  yellow: '#f1f5f9',
  orange: '#f1f5f9',
  slate: '#f1f5f9',
};

export const TAG_TEXT_COLORS: Record<TagColor, string> = {
  red: '#475569',
  blue: '#475569',
  green: '#475569',
  purple: '#475569',
  yellow: '#475569',
  orange: '#475569',
  slate: '#475569',
};
